services:
  frontend:
    build: 
      context: .
      dockerfile: ./Dockerfiles/frontend.Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - login-app-net

  backend:
    build: 
      context: .
      dockerfile: ./Dockerfiles/backend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://admin:admin@database:27017
      - JWT_SECRET=your_secret_key
    networks:
      - login-app-net

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - login-app-net

networks:
  login-app-net:
    driver: bridge

volumes:
  mongodb-data:
