apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: {{ .Values.database.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.env.POSTGRES_PASSWORD }}
          ports:
            - containerPort: {{ .Values.database.port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: database-pvc
