apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: login-app-qa
  namespace: argocd
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/pauljosepq/login-app-sample
    path: helm
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
