replicaCount: 1

backend:
  image: login-app-backend:1.0.0
  port: 3000

frontend:
  image: login-app-frontend:1.0.0
  port: 80

database:
  image: login-app-database:1.0.0 
  port: 5432
  persistence:
    enabled: true
    storageClass: standard
    size: 1Gi

ingress:
  enabled: true
  host: login-app.local
  backendPath: /api
  frontendPath: /

service:
  type: ClusterIP
