replicaCount: 1

backend:
  image: backend-image:latest
  port: 3000

frontend:
  image: frontend-image:latest
  port: 80

database:
  image: postgres:latest
  port: 5432
  env:
    POSTGRES_USER: "admin"
    POSTGRES_PASSWORD: "admin"

ingress:
  enabled: true
  host: login-app.local
  backendPath: /api
  frontendPath: /

database:
  persistence:
    enabled: true
    storageClass: standard
    size: 1Gi

service:
  type: ClusterIP
