name: Docker Image CI

on:
  release:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: pauljosepq
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Frontend Docker image
      run: docker build . --file Dockerfiles/frontend.Dockerfile --tag ghcr.io/pauljosepq/login-app-frontend:${{ github.ref_name }}

    - name: Push the Frontend Docker image to GitHub Container Registry
      run: docker push ghcr.io/pauljosepq/login-app-frontend:${{ github.ref_name }}

    - name: Build the Backend Docker image
      run: docker build . --file Dockerfiles/backend.Dockerfile --tag ghcr.io/pauljosepq/login-app-backend:${{ github.ref_name }}

    - name: Push the Backend Docker image to GitHub Container Registry
      run: docker push ghcr.io/pauljosepq/login-app-frontend:${{ github.ref_name }}

